services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app/app

    environment:
      - DATABASE_URL=${DATABASE_URL}
    
    ports:
      - "${APP_PORT}:8000"

    depends_on:
      - postgres

  postgres:
    image: postgres:latest

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: {}
